apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "no-apicurio"
  description: "no apicurio endpoint"
  tags:
    - java
spec:
  type: service
  lifecycle: experimental
  owner: "group:default/backstage-admins"
  system: system:default/quarkus
  consumesApis: 
    - openapi-skeleton